<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="irb1200_stick">

  <!-- ===== basic props ===== -->
  <xacro:property name="PI" value="3.141592653589793"/>
  <xacro:property name="r"  value="0.02"/>  <!-- cylinder radius -->
  <xacro:property name="m"  value="1.0"/>   <!-- kg per link   -->

  <!-- ===== ABB IRB1200-5/0.9 kinematic dims (m) ===== -->
  <xacro:property name="d1" value="0.210"/>  <!-- base → shoulder -->
  <xacro:property name="a2" value="0.399"/>  <!-- shoulder → arm  -->
  <xacro:property name="a3" value="0.448"/>  <!-- arm → forearm   -->
  <xacro:property name="l4" value="0.082"/>  <!-- wrist 1         -->
  <xacro:property name="l5" value="0.082"/>  <!-- wrist 2         -->
  <xacro:property name="l6" value="0.100"/>  <!-- flange          -->

  <!-- ===== inertia helper ===== -->
  <xacro:macro name="cyl_inertial" params="mass length">
    <inertial>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <!-- slender cylinder about X/Y; OK for a stick figure -->
      <inertia ixx="${(1/12.0)*mass*3*r*r + (1/2.0)*mass*r*r}"
               iyy="${(1/12.0)*mass*3*r*r + (1/2.0)*mass*r*r}"
               izz="${(1/2.0)*mass*r*r}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- ===== visual material ===== -->
  <material name="Grey"><color rgba="0.6 0.6 0.6 1"/></material>
  <material name="Blue"><color rgba="0.0 0.4 0.8 1"/></material>

  <!-- ===== link factory ===== -->
  <xacro:macro name="make_link" params="name length is_blue:=false">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
        <xacro:if value="${is_blue}"><material name="Blue"/></xacro:if>
        <xacro:unless value="${is_blue}"><material name="Grey"/></xacro:unless>
      </visual>
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
      </collision>
      <xacro:cyl_inertial mass="${m}" length="${length}"/>
    </link>
  </xacro:macro>

  <!-- ===== links ===== -->
  <link name="base_link">
    <visual><geometry><cylinder radius="0.05" length="0.05"/></geometry></visual>
  </link>
  <xacro:make_link name="link_1" length="${d1}"/>
  <xacro:make_link name="link_2" length="${a2}"/>
  <xacro:make_link name="link_3" length="${a3}"/>
  <xacro:make_link name="link_4" length="${l4}" is_blue="true"/>
  <xacro:make_link name="link_5" length="${l5}" is_blue="true"/>
  <xacro:make_link name="link_6" length="${l6}" is_blue="true"/>

  <!-- ===== joints ===== -->
  <joint name="joint_1" type="revolute">
    <parent link="base_link"/><child link="link_1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/><axis xyz="0 0 1"/>
    <limit effort="50" velocity="2" lower="-${PI}" upper="${PI}"/>
  </joint>

  <joint name="joint_2" type="revolute">
    <parent link="link_1"/><child link="link_2"/>
    <origin xyz="0 0 ${d1}" rpy="0 0 0"/><axis xyz="0 -1 0"/>
    <limit effort="50" velocity="2" lower="-2.5" upper="2.5"/>
  </joint>

  <joint name="joint_3" type="revolute">
    <parent link="link_2"/><child link="link_3"/>
    <origin xyz="0 0 ${a2}" rpy="0 0 0"/><axis xyz="0 -1 0"/>
    <limit effort="50" velocity="2" lower="-2.7" upper="2.7"/>
  </joint>

  <joint name="joint_4" type="revolute">
    <parent link="link_3"/><child link="link_4"/>
    <origin xyz="0 0 ${a3}" rpy="0 0 0"/><axis xyz="1 0 0"/>
    <limit effort="20" velocity="3" lower="-${PI}" upper="${PI}"/>
  </joint>

  <joint name="joint_5" type="revolute">
    <parent link="link_4"/><child link="link_5"/>
    <origin xyz="0 0 ${l4}" rpy="0 0 0"/><axis xyz="0 -1 0"/>
    <limit effort="20" velocity="3" lower="-${PI}" upper="${PI}"/>
  </joint>

  <joint name="joint_6" type="revolute">
    <parent link="link_5"/><child link="link_6"/>
    <origin xyz="0 0 ${l5}" rpy="0 0 0"/><axis xyz="1 0 0"/>
    <limit effort="20" velocity="3" lower="-${PI}" upper="${PI}"/>
  </joint>

  <!-- ===== ros2_control ===== -->
  <gazebo><plugin name="gz_ros2_control" filename="libgazebo_ros2_control.so"/></gazebo>

  <ros2_control name="irb1200_arm" type="system">
    <hardware><plugin>mock_components/GenericSystem</plugin></hardware>
    <joint name="joint_1"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="joint_2"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="joint_3"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="joint_4"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="joint_5"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="joint_6"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
  </ros2_control>

</robot>
