joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  publish_rate: 50

joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  command_interfaces: [position]
  state_interfaces:   [position, velocity]
